name: stepup-api
app: python@3.11
options:
  ports: 8000
  start: uvicorn main:app --host 0.0.0.0 --port $PORT
  health: /health
  env:
    - name: SUPABASE_URL
      value: https://xyrbiuogwtmcjwqkojrb.supabase.co
    - name: SUPABASE_KEY
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5cmJpdW9nd3RtY2p3cWtvanJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxOTA5NDUsImV4cCI6MjA3NDc2Njk0NX0.AFau_18T-iVIc9gIGoTbvOhq42H8VDfpJ0rKvmHfAHA
    - name: CORS_ORIGINS
      value: "*"
  buildenv: []
  install: pip install -r requirements.txt
context:
  git:
    url: https://github.com/Same-Ta/conpanion.git
    branch: back
